### ISSUE TITLE
ValueError: too many values to unpack (expected 4)

### ISSUE THREAD

**Issue by ryanandres** [lamoreauxlab/srpenergy-api-client-python#2]
There is an issue parsing the rows when the resultset returns the on/off peak status. I'm not sure if this is only outputted when the type of service is Time-of-use, which is what I am on.

Traceback (most recent call last):
  File ".\tester.py", line 10, in <module>
    usage = client.usage(start_date, end_date)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\srpenergy\client.py", line 215, in usage
    raise ex
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\srpenergy\client.py", line 206, in usage
    str_date, str_time, str_kwh, str_cost = row.split(',')
ValueError: too many values to unpack (expected 4)

Sample rows
12/1/2018,12:00 AM,2.6,$0.22,off-peak
12/1/2018,1:00 AM,2.9,$0.24,off-peak
12/1/2018,2:00 AM,2.7,$0.23,off-peak
12/1/2018,3:00 AM,2.7,$0.23,off-peak
12/1/2018,4:00 AM,1.9,$0.17,off-peak
12/1/2018,5:00 AM,1.2,$0.12,off-peak
12/1/2018,6:00 AM,1.4,$0.13,off-peak
12/1/2018,7:00 AM,1.6,$0.15,off-peak

**Comment by ryanandres** [comment]
The column is called Rate. Here is an excel export via the website:

Usage Date | Hour | kWh | Cost | Rate
11/26/2018 | 12:00 AM | 2.2 | $0.19 | off-peak
11/26/2018 | 1:00 AM | 2.8 | $0.24 | off-peak
11/26/2018 | 2:00 AM | 2.7 | $0.23 | off-peak
11/26/2018 | 3:00 AM | 2.8 | $0.23 | off-peak
11/26/2018 | 4:00 AM | 1.9 | $0.17 | off-peak
11/26/2018 | 5:00 AM | 1.3 | $0.17 | on-peak
11/26/2018 | 6:00 AM | 1.5 | $0.20 | on-peak

**Comment by briglx** [comment]
Fixed with the pull request

**Comment by briglx** [comment]
Will do... I have one in the works

**Comment by briglx** [comment]
Done

**Comment by ryanandres** [comment]
Thanks!
