### ISSUE TITLE
Empty data set

### ISSUE THREAD

**Issue by atowarnyckyj** [lamoreauxlab/srpenergy-api-client-python#4]
Is the SRP API still supported by SRP? I'm receiving results but all values are empty.

`[('06/17/2020', '00:00 AM', '2020-06-17T00:00:00', 0.0, 0.0), ('06/17/2020', '01:00 AM', '2020-06-17T01:00:00', 0.0, 0.0), ('06/17/2020', '02:00 AM', '2020-06-17T02:00:00', 0.0, 0.0), ('06/17/2020', '03:00 AM', '2020-06-17T03:00:00', 0.0, 0.0), ('06/17/2020', '04:00 AM', '2020-06-17T04:00:00', 0.0, 0.0), ('06/17/2020', '05:00 AM', '2020-06-17T05:00:00', 0.0, 0.0), ('06/17/2020', '06:00 AM', '2020-06-17T06:00:00', 0.0, 0.0), ('06/17/2020', '07:00 AM', '2020-06-17T07:00:00', 0.0, 0.0), ('06/17/2020', '08:00 AM', '2020-06-17T08:00:00', 0.0, 0.0), ('06/17/2020', '09:00 AM', '2020-06-17T09:00:00', 0.0, 0.0), ('06/17/2020', '10:00 AM', '2020-06-17T10:00:00', 0.0, 0.0), ('06/17/2020', '11:00 AM', '2020-06-17T11:00:00', 0.0, 0.0), ('06/17/2020', '12:00 PM', '2020-06-17T12:00:00', 0.0, 0.0), ('06/17/2020', '13:00 PM', '2020-06-17T13:00:00', 0.0, 0.0), ('06/17/2020', '14:00 PM', '2020-06-17T14:00:00', 0.0, 0.0), ('06/17/2020', '15:00 PM', '2020-06-17T15:00:00', 0.0, 0.0), ('06/17/2020', '16:00 PM', '2020-06-17T16:00:00', 0.0, 0.0), ('06/17/2020', '17:00 PM', '2020-06-17T17:00:00', 0.0, 0.0), ('06/17/2020', '18:00 PM', '2020-06-17T18:00:00', 0.0, 0.0), ('06/17/2020', '19:00 PM', '2020-06-17T19:00:00', 0.0, 0.0), ('06/17/2020', '20:00 PM', '2020-06-17T20:00:00', 0.0, 0.0), ('06/17/2020', '21:00 PM', '2020-06-17T21:00:00', 0.0, 0.0), ('06/17/2020', '22:00 PM', '2020-06-17T22:00:00', 0.0, 0.0), ('06/17/2020', '23:00 PM', '2020-06-17T23:00:00', 0.0, 0.0), ('06/18/2020', '00:00 AM', '2020-06-18T00:00:00', 0.0, 0.0), ('06/18/2020', '01:00 AM', '2020-06-18T01:00:00', 0.0, 0.0), ('06/18/2020', '02:00 AM', '2020-06-18T02:00:00', 0.0, 0.0), ('06/18/2020', '03:00 AM', '2020-06-18T03:00:00', 0.0, 0.0), ('06/18/2020', '04:00 AM', '2020-06-18T04:00:00', 0.0, 0.0), ('06/18/2020', '05:00 AM', '2020-06-18T05:00:00', 0.0, 0.0), ('06/18/2020', '06:00 AM', '2020-06-18T06:00:00', 0.0, 0.0), ('06/18/2020', '07:00 AM', '2020-06-18T07:00:00', 0.0, 0.0), ('06/18/2020', '08:00 AM', '2020-06-18T08:00:00', 0.0, 0.0), ('06/18/2020', '09:00 AM', '2020-06-18T09:00:00', 0.0, 0.0), ('06/18/2020', '10:00 AM', '2020-06-18T10:00:00', 0.0, 0.0), ('06/18/2020', '11:00 AM', '2020-06-18T11:00:00', 0.0, 0.0), ('06/18/2020', '12:00 PM', '2020-06-18T12:00:00', 0.0, 0.0), ('06/18/2020', '13:00 PM', '2020-06-18T13:00:00', 0.0, 0.0), ('06/18/2020', '14:00 PM', '2020-06-18T14:00:00', 0.0, 0.0), ('06/18/2020', '15:00 PM', '2020-06-18T15:00:00', 0.0, 0.0), ('06/18/2020', '16:00 PM', '2020-06-18T16:00:00', 0.0, 0.0), ('06/18/2020', '17:00 PM', '2020-06-18T17:00:00', 0.0, 0.0), ('06/18/2020', '18:00 PM', '2020-06-18T18:00:00', 0.0, 0.0), ('06/18/2020', '19:00 PM', '2020-06-18T19:00:00', 0.0, 0.0), ('06/18/2020', '20:00 PM', '2020-06-18T20:00:00', 0.0, 0.0), ('06/18/2020', '21:00 PM', '2020-06-18T21:00:00', 0.0, 0.0), ('06/18/2020', '22:00 PM', '2020-06-18T22:00:00', 0.0, 0.0), ('06/18/2020', '23:00 PM', '2020-06-18T23:00:00', 0.0, 0.0)]`

**Comment by briglx** [comment]
Looks like they've added an additional cookie with the auth. Let me see if I can update. I'm getting data through postman with the url: https://myaccount.srpnet.com/myaccountapi/api/usage/dailyusagedetail?billaccount=

**Comment by briglx** [comment]
I was able to test and retrieve data through the api. One thing I noticed is I had to change my accountId format to not include hyphens. I don't know if that is your case.

**Comment by atowarnyckyj** [comment]
I must be doing something wrong on my end. I'm able to get a valid login (I've been using the non-hyphened account since I installed as the hyphened one failed)

`>>> from srpenergy.client import SrpEnergyClient
>>> from datetime import datetime, timedelta
>>>
>>> # Your SRP user account and password
... accountid = "*********"
>>> username = "****"
>>> password = "****"
>>> end_date = datetime.now()
>>> start_date = datetime.now() - timedelta(days=2)
>>>
>>> # Setup client
... client = SrpEnergyClient(accountid, username, password)
>>> valid = client.validate()
>>> print(valid)
True`

The dates and times show up in the usage variable, they're just zeroes.

`>>> usage = client.usage(start_date, end_date)
>>> for i in usage:
...    print(i)
...
('06/22/2020', '00:00 AM', '2020-06-22T00:00:00', 0.0, 0.0)
('06/22/2020', '01:00 AM', '2020-06-22T01:00:00', 0.0, 0.0)
('06/22/2020', '02:00 AM', '2020-06-22T02:00:00', 0.0, 0.0)
('06/22/2020', '03:00 AM', '2020-06-22T03:00:00', 0.0, 0.0)
('06/22/2020', '04:00 AM', '2020-06-22T04:00:00', 0.0, 0.0)
('06/22/2020', '05:00 AM', '2020-06-22T05:00:00', 0.0, 0.0)
('06/22/2020', '06:00 AM', '2020-06-22T06:00:00', 0.0, 0.0)
('06/22/2020', '07:00 AM', '2020-06-22T07:00:00', 0.0, 0.0)
('06/22/2020', '08:00 AM', '2020-06-22T08:00:00', 0.0, 0.0)
('06/22/2020', '09:00 AM', '2020-06-22T09:00:00', 0.0, 0.0)
('06/22/2020', '10:00 AM', '2020-06-22T10:00:00', 0.0, 0.0)
('06/22/2020', '11:00 AM', '2020-06-22T11:00:00', 0.0, 0.0)
('06/22/2020', '12:00 PM', '2020-06-22T12:00:00', 0.0, 0.0)
('06/22/2020', '13:00 PM', '2020-06-22T13:00:00', 0.0, 0.0)
('06/22/2020', '14:00 PM', '2020-06-22T14:00:00', 0.0, 0.0)
('06/22/2020', '15:00 PM', '2020-06-22T15:00:00', 0.0, 0.0)
('06/22/2020', '16:00 PM', '2020-06-22T16:00:00', 0.0, 0.0)
('06/22/2020', '17:00 PM', '2020-06-22T17:00:00', 0.0, 0.0)
('06/22/2020', '18:00 PM', '2020-06-22T18:00:00', 0.0, 0.0)
('06/22/2020', '19:00 PM', '2020-06-22T19:00:00', 0.0, 0.0)
('06/22/2020', '20:00 PM', '2020-06-22T20:00:00', 0.0, 0.0)
('06/22/2020', '21:00 PM', '2020-06-22T21:00:00', 0.0, 0.0)
('06/22/2020', '22:00 PM', '2020-06-22T22:00:00', 0.0, 0.0)
('06/22/2020', '23:00 PM', '2020-06-22T23:00:00', 0.0, 0.0)
('06/23/2020', '00:00 AM', '2020-06-23T00:00:00', 0.0, 0.0)
('06/23/2020', '01:00 AM', '2020-06-23T01:00:00', 0.0, 0.0)
('06/23/2020', '02:00 AM', '2020-06-23T02:00:00', 0.0, 0.0)
('06/23/2020', '03:00 AM', '2020-06-23T03:00:00', 0.0, 0.0)
('06/23/2020', '04:00 AM', '2020-06-23T04:00:00', 0.0, 0.0)
('06/23/2020', '05:00 AM', '2020-06-23T05:00:00', 0.0, 0.0)
('06/23/2020', '06:00 AM', '2020-06-23T06:00:00', 0.0, 0.0)
('06/23/2020', '07:00 AM', '2020-06-23T07:00:00', 0.0, 0.0)
('06/23/2020', '08:00 AM', '2020-06-23T08:00:00', 0.0, 0.0)
('06/23/2020', '09:00 AM', '2020-06-23T09:00:00', 0.0, 0.0)
('06/23/2020', '10:00 AM', '2020-06-23T10:00:00', 0.0, 0.0)
('06/23/2020', '11:00 AM', '2020-06-23T11:00:00', 0.0, 0.0)
('06/23/2020', '12:00 PM', '2020-06-23T12:00:00', 0.0, 0.0)
('06/23/2020', '13:00 PM', '2020-06-23T13:00:00', 0.0, 0.0)
('06/23/2020', '14:00 PM', '2020-06-23T14:00:00', 0.0, 0.0)
('06/23/2020', '15:00 PM', '2020-06-23T15:00:00', 0.0, 0.0)
('06/23/2020', '16:00 PM', '2020-06-23T16:00:00', 0.0, 0.0)
('06/23/2020', '17:00 PM', '2020-06-23T17:00:00', 0.0, 0.0)
('06/23/2020', '18:00 PM', '2020-06-23T18:00:00', 0.0, 0.0)
('06/23/2020', '19:00 PM', '2020-06-23T19:00:00', 0.0, 0.0)
('06/23/2020', '20:00 PM', '2020-06-23T20:00:00', 0.0, 0.0)
('06/23/2020', '21:00 PM', '2020-06-23T21:00:00', 0.0, 0.0)
('06/23/2020', '22:00 PM', '2020-06-23T22:00:00', 0.0, 0.0)
('06/23/2020', '23:00 PM', '2020-06-23T23:00:00', 0.0, 0.0)`

I would run this through Postman but I'm not clear on the authorization methods. Do you know if there's documentation on the SRP API? I couldn't find it anywhere.

**Comment by briglx** [comment]
What do you see in the browser inspector when you navigate to srp and click on the hourly usage tab of the chart? There should be an XHR request to `https://myaccount.srpnet.com/myaccountapi/api/usage/hourlydetail?billaccount=....`

I can see that I have data on mine.

![SRPData](https://user-images.githubusercontent.com/1304774/85769571-f64d4a00-b6ce-11ea-8cdf-f28940c2947d.PNG)

**Comment by atowarnyckyj** [comment]
I believe I found one of the key differences: I'm on Time of Use, not Basic.

It looks like the request is correct but the response is different.

Request: 
Request URL:https://myaccount.srpnet.com/myaccountapi/api/usage/hourlydetail?billaccount=*********&beginDate=06-23-2020&endDate=06-24-2020
Request Method:GET
Remote Address:148.126.100.62:443
Status Code:
200
Version:HTTP/1.1
Referrer Policy:strict-origin-when-cross-origin

Response:
<img width="2556" alt="Untitled" src="https://user-images.githubusercontent.com/67170716/85772769-07e42100-b6d2-11ea-9c5b-f171bed1ab52.png">

Here are all the JSON objects being returned:
<img width="463" alt="image" src="https://user-images.githubusercontent.com/67170716/85772876-221dff00-b6d2-11ea-9462-d412c25b7947.png">
<img width="655" alt="image" src="https://user-images.githubusercontent.com/67170716/85772991-3f52cd80-b6d2-11ea-8bba-b4c4042d2836.png">
<img width="629" alt="image" src="https://user-images.githubusercontent.com/67170716/85773029-47ab0880-b6d2-11ea-816f-0f99a120235a.png">


It looks like with my current plan, they won't give me hourly costs, just usage statistics. I might still be able to use this to calculate hourly usage, just not cost associated.

**Comment by briglx** [comment]
can you send me the full json response? I'd like to incorporate something if possible.

**Comment by atowarnyckyj** [comment]
I sent it via email. If that doesn't work for you, let me know and I'll post it here.

**Comment by briglx** [comment]
I've made an update that can now handle the time of use use case. I'll be updating pypi in the next week.

**Comment by ryanandres** [comment]
SRP has TOU and TOU Demand plans:
https://www.srpnet.com/prices/home/tou.aspx
https://www.srpnet.com/prices/home/residentialdemand.aspx

Not sure if their output is the same, but here are the hourly and daily for TOU demand
[dailyusagedetail.txt](https://github.com/lamoreauxlab/srpenergy-api-client-python/files/4847905/dailyusagedetail.txt)
[hourlydetail.txt](https://github.com/lamoreauxlab/srpenergy-api-client-python/files/4847907/hourlydetail.txt)

**Comment by briglx** [comment]
I was using the tou rates for this release.

**Comment by atowarnyckyj** [comment]
I will test and close if successful. Thank you very much for looking into this.

**Comment by briglx** [comment]
I've deployed to pypi. Please use version pip install srpenergy==1.3.2

**Comment by atowarnyckyj** [comment]
This worked. Thank you very much.

`('06/30/2020', '00:00 AM', '2020-06-30T00:00:00', 5.1, 0.37)`
`('06/30/2020', '01:00 AM', '2020-06-30T01:00:00', 5.0, 0.36)`
`('06/30/2020', '02:00 AM', '2020-06-30T02:00:00', 5.1, 0.37)`
`('06/30/2020', '03:00 AM', '2020-06-30T03:00:00', 4.1, 0.3)`
`('06/30/2020', '04:00 AM', '2020-06-30T04:00:00', 4.6, 0.33)`
`('06/30/2020', '05:00 AM', '2020-06-30T05:00:00', 5.0, 0.36)`
`('06/30/2020', '06:00 AM', '2020-06-30T06:00:00', 4.2, 0.31)`
`('06/30/2020', '07:00 AM', '2020-06-30T07:00:00', 5.0, 0.36)`
`('06/30/2020', '08:00 AM', '2020-06-30T08:00:00', 4.7, 0.34)`
`('06/30/2020', '09:00 AM', '2020-06-30T09:00:00', 4.2, 0.31)`
`('06/30/2020', '10:00 AM', '2020-06-30T10:00:00', 5.5, 0.4)`
`('06/30/2020', '11:00 AM', '2020-06-30T11:00:00', 5.9, 0.43)`
`('06/30/2020', '12:00 PM', '2020-06-30T12:00:00', 9.1, 0.66)`
`('06/30/2020', '13:00 PM', '2020-06-30T13:00:00', 9.0, 0.65)`
`('06/30/2020', '14:00 PM', '2020-06-30T14:00:00', 2.9, 0.61)`
`('06/30/2020', '15:00 PM', '2020-06-30T15:00:00', 4.9, 1.03)`
`('06/30/2020', '16:00 PM', '2020-06-30T16:00:00', 6.6, 1.38)`
`('06/30/2020', '17:00 PM', '2020-06-30T17:00:00', 6.3, 1.32)`
`('06/30/2020', '18:00 PM', '2020-06-30T18:00:00', 6.3, 1.32)`
`('06/30/2020', '19:00 PM', '2020-06-30T19:00:00', 3.7, 0.77)`
`('06/30/2020', '20:00 PM', '2020-06-30T20:00:00', 7.5, 0.55)`
`('06/30/2020', '21:00 PM', '2020-06-30T21:00:00', 6.5, 0.47)`
`('06/30/2020', '22:00 PM', '2020-06-30T22:00:00', 6.5, 0.47)`
`('06/30/2020', '23:00 PM', '2020-06-30T23:00:00', 5.3, 0.39)`
`('07/01/2020', '00:00 AM', '2020-07-01T00:00:00', 5.1, 0.37)`
`('07/01/2020', '01:00 AM', '2020-07-01T01:00:00', 4.3, 0.31)`
`('07/01/2020', '02:00 AM', '2020-07-01T02:00:00', 4.6, 0.34)`
`('07/01/2020', '03:00 AM', '2020-07-01T03:00:00', 4.7, 0.34)`
`('07/01/2020', '04:00 AM', '2020-07-01T04:00:00', 4.1, 0.3)`
`('07/01/2020', '05:00 AM', '2020-07-01T05:00:00', 4.1, 0.3)`
`('07/01/2020', '06:00 AM', '2020-07-01T06:00:00', 4.4, 0.32)`
`('07/01/2020', '07:00 AM', '2020-07-01T07:00:00', 4.7, 0.34)`
`('07/01/2020', '08:00 AM', '2020-07-01T08:00:00', 4.9, 0.36)`
`('07/01/2020', '09:00 AM', '2020-07-01T09:00:00', 5.3, 0.39)`
`('07/01/2020', '10:00 AM', '2020-07-01T10:00:00', 4.8, 0.35)`
`('07/01/2020', '11:00 AM', '2020-07-01T11:00:00', 5.7, 0.42)`
`('07/01/2020', '12:00 PM', '2020-07-01T12:00:00', 9.3, 0.68)`
`('07/01/2020', '13:00 PM', '2020-07-01T13:00:00', 8.5, 0.62)`
`('07/01/2020', '14:00 PM', '2020-07-01T14:00:00', 2.9, 0.7)`
`('07/01/2020', '15:00 PM', '2020-07-01T15:00:00', 5.7, 1.37)`
`('07/01/2020', '16:00 PM', '2020-07-01T16:00:00', 7.2, 1.73)`
`('07/01/2020', '17:00 PM', '2020-07-01T17:00:00', 6.1, 1.47)`
`('07/01/2020', '18:00 PM', '2020-07-01T18:00:00', 6.7, 1.61)`
`('07/01/2020', '19:00 PM', '2020-07-01T19:00:00', 3.9, 0.94)`
`('07/01/2020', '20:00 PM', '2020-07-01T20:00:00', 7.4, 0.54)`
`('07/01/2020', '21:00 PM', '2020-07-01T21:00:00', 7.1, 0.52)`
`('07/01/2020', '22:00 PM', '2020-07-01T22:00:00', 6.7, 0.49)`
`('07/01/2020', '23:00 PM', '2020-07-01T23:00:00', 6.3, 0.46)`
