### ISSUE TITLE
Home Assistant Custom Component(s)

### ISSUE THREAD

**Issue by mrand** [lamoreauxlab/srpenergy-api-client-python#6]
As I'm sure you know, the SRP integration was removed from Home Assistant as part of their move away form web scrapers.  Not sure if you are aware, but custom components offers it, however it's currently broken because it's still pinned to an old version: https://github.com/custom-components/srp_energy/issues/1

It appears there are some people still wanting to use it though - would you consider updating the version in custom components?  Or is there a "better" way for Home Assistant users to use your work?

**Comment by briglx** [comment]
There is a pull request for a new integration https://github.com/home-assistant/core/pull/41091

**Comment by briglx** [comment]
This is now part of the 2020.12 release https://github.com/home-assistant/core/releases/tag/2020.12.1
